id: P000815
initial_creation_type: ebook
source_metadata:
  title: Tsadra-test
  subtitle: test subtitle
  authors:
  - test-author
  collection: test
  publisher: Test publisher
  id: SKU-TSD-01
  cover: tmpmzdlqn_o.jpg
  credit: tmpq6iqx0kj.jpg
